name: Multihost Build Lab2

on:
  push:
    branches:
      - lab2  # Теперь пайплайн сработает только при пуше в эту ветку
  pull_request:
    branches:
      - lab2  # И при создании PR, целью которого является lab2

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Compile ip_filter
        # Используем относительный путь, если файл лежит в корне или папке lab2
        run: |
          g++ -std=c++11 ip_filter.cpp -o ip_filter

      - name: Test Execution
        run: |
          ./ip_filter < ip_filter.tsv > result.tsv
          # Просто выведем первые строки, чтобы убедиться в успешности
          head -n 5 result.tsv