name: Build Releases

on:
  push:
    branches: [ "lab3" ]
  pull_request:
    branches: [ "lab3" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      # Матрица для сборки на двух ОС
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      # Создаем папку сборки и конфигурируем проект
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      # Запускаем компиляцию
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      # Опционально: запуск программы для проверки работоспособности
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ./build/Release/containers_lab.exe
        else
          ./build/containers_lab
        fi