name: C++ Auto-Release CI

on:
  push:
    branches:
      - lab4
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir -p output
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            # На Windows CMake часто кладет бинарник в папку Release
            cp build/Release/*.exe output/allocator_lab_win.exe || cp build/*.exe output/allocator_lab_win.exe
          else
            cp build/allocator_lab output/allocator_lab_macos || echo "Binary not found"
          fi

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          # Автоматический номер релиза на основе счетчика запусков GitHub Actions
          tag_name: "v0.1.${{ github.run_number }}"
          name: "Release v0.1.${{ github.run_number }}"
          body: "Автоматическая сборка коммита ${{ github.sha }}"
          files: output/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}