name: Multihost Build Lab4

on:
  push:
    branches:
      - lab4

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean Environment
        shell: bash
        run: rm -rf build # Удаляем папку build, если она была закоммичена случайно

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir -p output
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Проверка стандартных путей Windows
            if [ -f "build/Release/lab4.exe" ]; then
              cp build/Release/lab4.exe output/allocator_lab_win.exe
            else
              cp build/lab4.exe output/allocator_lab_win.exe
            fi
          else
            # Для Ubuntu
            cp build/lab4 output/allocator_lab_ubuntu
          fi

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v0.1.${{ github.run_number }}"
          name: "Release v0.1.${{ github.run_number }}"
          body: "Автоматическая сборка для лабораторной №4. ОС: Windows и Ubuntu."
          files: output/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}