name: 'lab5'

on:
  push:
    branches:
      - lab5
      - feature/github_actions
  release:
    types: [published]

jobs:
  build_on_Ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsfml-dev

      - name: Build and Package
        run: |
          mkdir build
          cd build
          cmake .. -DPATCH_VERSION=${{ github.run_number }} -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          cmake --build . --target package

      - name: Run Tests
        run: |
          cd build
          ctest -V

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: v0.0.${{ github.run_number }}-linux
          files: build/physics-0.0.${{ github.run_number }}-Linux.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install SFML
        run: brew install sfml

      - name: Build and Package
        run: |
          mkdir build
          cd build
          # Указываем путь к SFML из brew, чтобы CMake точно его увидел
          cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix sfml) \
                   -DPATCH_VERSION=${{ github.run_number }} \
                   -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          cmake --build . --target package

      - name: Run Tests
        run: |
          cd build
          ctest -C Release

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: v0.0.${{ github.run_number }}-mac
          files: build/physics-0.0.${{ github.run_number }}-Darwin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}