name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions
      - lab1 #воркфлоу ветки lab1

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # Добавили матрицу ОС
    runs-on: ${{ matrix.os }} # Используем переменную из матрицы
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Установка Boost только для Ubuntu (на macOS он ставится иначе или уже есть)
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      # На macOS используем brew для Boost
      - if: matrix.os == 'macos-latest'
        run: brew install boost

      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      
      - name: Check version output
        run: ./helloworld_cli
        
      - run: cmake --build . --target test

      # Шаги ниже (Package и Release) выполняем ТОЛЬКО на Ubuntu, 
      # чтобы не дублировать релизы и избежать ошибок путей .deb
      - if: matrix.os == 'ubuntu-latest'
        run: cmake --build . --target package

      - name: Create Release
        if: matrix.os == 'ubuntu-latest'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: matrix.os == 'ubuntu-latest'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./helloworld-1.0.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-1.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package