name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions
      - lab1

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Установка зависимостей
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      - if: matrix.os == 'macos-latest'
        run: brew install boost

      # Сборка
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      
      - name: Check version output
        run: ./helloworld_cli
        
      - run: cmake --build . --target test

      # Создание пакетов
      - name: Build package
        run: cmake --build . --target package

      # Находим имя созданного файла (оно может отличаться на разных ОС)
      - name: Identify artifact
        id: artifact_info
        shell: bash
        run: |
          # Ищем файл, который создал CPack (deb для Linux, dmg/tar.gz для Mac)
          FILENAME=$(ls helloworld-1.0.${{ github.run_number }}-*.* | head -n 1)
          echo "artifact_path=$FILENAME" >> $GITHUB_OUTPUT
          echo "artifact_name=$(basename $FILENAME)" >> $GITHUB_OUTPUT

      # Создание релиза (делает ТОЛЬКО Ubuntu, чтобы не было конфликтов)
      - name: Create Release
        if: matrix.os == 'ubuntu-latest'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      # Загрузка артефактов (Ubuntu загружает в свой релиз, Mac в созданный Ubuntu)
      # Используем специальный экшен, который умеет загружать в существующий релиз
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_number }}
          files: ${{ steps.artifact_info.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}